name: Java CI-pipelines

on:
  push:
    branches: [ develop, main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone git repo
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
